### PR TITLE
I hope I did this correctly

### PR DESCRIPTION
**Pull request by senmu**
I re-pulled the latest changes and merged into the master branch. Hopefully I did this correctly... (sorry, it's my first time submitting a pull request)

### CODE REVIEW

**Comment by plamoni** [comment]
We're in the process of rethinking how the plugin system will work... don't work too hard on fixing this :-)

**Comment by senmu** [comment]
Haha alright, thanks for the heads up.

On 2011-11-21, at 20:11, Pete
reply@reply.github.com
wrote:

**Comment by senmu** [comment]
I removed a lot of the redundancy in the speech_recognized method. Checking for alternative names (eg. city or team nicknames) has been replaced by a method that will return a team name. Would this work? Or do you know of a data structure or alternative technique that could replace the pickOutTeam(phrase) method better (in commit f3a1376)?

**Comment by plamoni** [comment]
It looks good, but hold on for now. We're considering some radical changes to how plugins work and I don't want to pull you in then delete you. :-)

**Pull request closed without merging**
