### PR TITLE
fix dns.rb

### PR DESCRIPTION
**Pull request by akston**
Removed _host variable from regex block. Probably hacky but it works for now. Thanks to HaroldW.

### CODE REVIEW

**Comment by plamoni** [comment]
Sounds like this change has to do with RubyDNS 0.6.0 and the fix would break RubyDNS <0.6.0. Therefore, can you update `siriproxy.gemspec` to require RubyDNS 0.6.0? Then I'll be happy to merge.

**Comment by ioquatix** [comment]
Hi, I'd probably recommend "~> 0.6.0" as it is less likely to break in the future.

**Comment by betarelease** [comment]
Can you please push this commit to rubygems? I have a raspberry pi image with siriproxy and that is broken. Need to install siriproxy with the fix for dns.rb.

Thanks

**Comment by elvisimprsntr** [comment]
Perform 
`siriproxy update`

**Pull request merged**
