### PR TITLE
Easier loading of plugins

### PR DESCRIPTION
**Pull request by wrboyce**

### CODE REVIEW

**Comment by wrboyce** [comment]
To load a plugin, symlink the plugin dir (so plugins/testproxy) into plugins-active (leaving you with plugins-active/testproxy/testproxy.rb)

**Comment by plamoni** [comment]
Okay, so the one issue that I have with this is that it doesn't have a good way of ordering plugin precedence. So if someone includes the Eliza plugin (which responds to everything and is very disruptive), they have no way of noting that they want that to go LAST (after other plugins get a shot at the query).

It's a small issue. But I'm also holding off for a little bit due to the potential refactoring of how plugins work. I'm leaving the pull request open for now as a reminder. :-)

Thanks!!!

**Comment by oncleben31** [comment]
If you are workin g on a refactoring I suggest an idea for plugin :
- Plugins should be launch dynamically as independent process by the server .
- If a plugin crash the server should not crash. The server catch the error and perhaps can relaunch the plugin or set it in standby
- If a plugin is modified or if a plugin is added to the plugin directory, the server should launch it without killing and relaunching the server.

Good work keep going ;-)

**Comment by netpro2k** [comment]
In the refactored branch you will see that plugins are now configured in config.yaml. We have decided that all plugins should be exposed as gems. In doing this we can automatically manage plugin dependancies and even install them just by adding them to the config file. This is not set in stone yet, but seems to be a reasonable direction.

We have not yet finalized how plugin API will look, but we certainly agree with the concerns raised here and are considering them (come join the discussion in irc if you want to contribute ideas)

**Comment by szomo** [comment]
Right now , i can't load any of the plugins , again i must be missing something obvious but just uncommenting 

name: 'Example'
path: './plugins/siriproxy-example'

and running bundle
doesn't work for me . I'm watching my interaction with the phone being read and transmitting information but Plugins Loaded : []

**Pull request closed without merging**
